---
- name: Machine Playbook
  hosts: test-machine.local.net
  gather_facts: true
  become: true
  vars:
    auto_start: false
    auto_start_no_prompt: false
    auto_provision: true
    skip_bootstrap: false
    
    config:
      os_type: RedHat_64
      box: 'berttejeda/oel7-lxc-x64'
      connection_timeout: 60
      hostname: <%= $VMDefinitionFile.BaseName %>
      ssh:
        inject_insecure_key: true
        username: vagrant
        password: vagrant
    desktop: false
    network_interfaces:
      - name: eth1
        ip: 192.168.56.250
        mask: 255.255.255.0
        auto_config: true
        method: 'private_network'
        dns:
          aliases:
            - test
    port_forwards:
      - name: testing
        host: 9999
        guest: 9999
        host_ip: 0.0.0.0
        guest_ip: 0.0.0.0
    provider:
      type: virtualbox
      virtualbox:
        modifyvm:
          name: <%= $VMDefinitionFile.BaseName %>
          natdnshostresolver1: 'on'
          cpus: 1
          memory: 1024
          vram: 16
        setextradata:
          VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
    shared_folders:
      - name: Documents
        host_path: <%= $env:USERPROFILE  %>\Documents
        
  roles:
    - role: system/setup
      vars:
        machine_name: '{{ ansible_play_batch | first }}'
        set_hostname: true
        disable_network_manager: true
        configure_network_interfaces: true
      tags:
        - system.setup  
    - role: users
    - role: ansible
      tags:
        - ansible.setup    